paths:
    jquery: 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min'
    bootstrap: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min'
#    selectize: 'https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/standalone/selectize.min'
    stache: 'stache'
    velocity: 'https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.min'
shim:
    jquery:
        exports: '$'
    underscore:
        exports: '_'
    backbone:
        deps: ['underscore', 'jquery']
        exports: 'Backbone'
    bootstrap:
        deps: ['jquery']
        exports: 'bootstrap'
#    selectize:
#        deps: ['jquery']
#        exports: 'selectize'
    velocity:
        exports: 'velocity'
modules:
    - name: 'application'

