paths:
    jquery: 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min'
    bootstrap: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min'
    stache: 'stache'
    eventbroker: 'backbone-eventbroker'
shim:
    jquery:
        exports: '$'
    underscore:
        exports: '_'
    backbone:
        deps: ['underscore', 'jquery']
        exports: 'Backbone'
    bootstrap:
        deps: ['jquery']
        exports: 'bootstrap'
    eventbroker:
        deps: ['backbone']
        exports: 'Backbone.EventBroker'
modules:
    - name: 'application'

