paths:
    jquery: 'jquery.min'
    bootstrap: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min'
    stache: 'stache'
    velocity: 'https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.min'
    owl-carousel: 'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min'
    dotdotdot: 'https://cdnjs.cloudflare.com/ajax/libs/jQuery.dotdotdot/1.7.4/jquery.dotdotdot.min'
shim:
    jquery:
        exports: '$'
    underscore:
        exports: '_'
    backbone:
        deps: ['underscore', 'jquery']
        exports: 'Backbone'
    bootstrap:
        deps: ['jquery']
        exports: 'bootstrap'
    velocity:
        deps: ['jquery']
        exports: 'velocity'
    dotdotdot:
        deps: ['jquery']
        exports: 'dotdotdot'
modules:
    - name: 'application'

