waitSeconds: 30
enforceDefine: true

paths:
    jquery: 'jquery.min'
    bootstrap: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min'
    stache: 'stache'
    velocity: 'https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.min'
    owl-carousel: 'https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min'
    dotdotdot: 'https://cdnjs.cloudflare.com/ajax/libs/jQuery.dotdotdot/1.7.4/jquery.dotdotdot.min'
    toggle: 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min'
    timeago: 'https://cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.4.3/jquery.timeago.min'
    moment: 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min'
    backbone-eventbroker: 'http://sourcehoney.s3-website-us-west-1.amazonaws.com/js/backbone-eventbroker'
    selectize: 'http://sourcehoney.s3-website-us-west-1.amazonaws.com/js/selectize'
    tabs: 'http://sourcehoney.s3-website-us-west-1.amazonaws.com/js/tabs'
    jquery-transit: 'http://sourcehoney.s3-website-us-west-1.amazonaws.com/js/jquery-transit'
    marked: 'https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min'
    linkify: 'https://cdnjs.cloudflare.com/ajax/libs/jQuery-linkify/1.1.7/jquery.linkify.min'

shim:
    jquery:
        exports: '$'
    underscore:
        exports: '_'
    backbone:
        deps: ['underscore', 'jquery']
        exports: 'Backbone'
    bootstrap:
        deps: ['jquery']
        exports: 'bootstrap'
    velocity:
        deps: ['jquery']
        exports: 'velocity'
    dotdotdot:
        deps: ['jquery']
        exports: 'dotdotdot'
    toggle:
        deps: ['jquery']
        exports: 'toggle'
    timeago:
        deps: ['jquery']
        exports: 'timeago'
    moment:
        deps: ['jquery']
        exports: 'moment'
    backbone-eventbroker:
        deps: ['jquery']
        exports: 'backbone-eventbroker'
    selectize:
        deps: ['jquery']
        exports: 'selectize'
    tabs:
        deps: ['jquery']
        exports: 'tabs'
    jquery-transit:
        deps: ['jquery']
        exports: 'jquery-transit'
    marked:
        deps: ['jquery']
        exports: 'marked'
    linkify:
        deps: ['jquery']
        exports: 'linkify'

modules:
    - name: 'application'

