paths:
    stache: 'stache'
    eventbroker: 'backbone-eventbroker'
shim:
    backbone:
        deps: ['underscore', 'jquery']
        exports: 'Backbone'
    underscore:
        exports: '_'
    bootstrap:
        deps: ['jquery']
    eventbroker:
        deps: ['backbone']
        exports: 'Backbone.EventBroker'
modules:
    - name: 'application'

